name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-scan:
    name: Build, Scan, and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image
      - name: Build Docker Image
        run: docker build -t idanohh/finwiz .

      # Step 4: Install Snyk CLI
      - name: Install Snyk CLI
        run: npm install -g snyk

      # Step 5: Authenticate Snyk CLI
      - name: Authenticate Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} # Snyk API token from GitHub Secrets
        run: snyk auth $SNYK_TOKEN

      # Step 6: Scan Docker Image with Snyk
      - name: Snyk Docker Image Scan
        run: snyk container test idanohh/finwiz

      # Step 7: Push the Docker image to Docker Hub
      - name: Push Docker Image
        run: docker push idanohh/finwiz
